#ifndef YTANNOTATORCORE_GLOBAL_H
#define YTANNOTATORCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(YTANNOTATORCORE_LIBRARY)
#  define YTANNOTATORCORE_EXPORT Q_DECL_EXPORT
#else
#  define YTANNOTATORCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // YTANNOTATORCORE_GLOBAL_H
